#!/bin/bash

# Tsubasa
# Script for sharing screenshots and/or status updates using [ihabunek/toot](https://github.com/ihabunek/toot)

basename="$(basename $0)"
message=
verbosity=0

check_verbosity() {
	if [ $verbosity -eq 1 ]; then
		echo "$1"
	fi
}

usage() {
	cat <<EOF
Usage:
	$basename [OPTION...] <command>

Help Options:
	-h	Show help options
	-V	Print version information and exit
	-v	Print debug logging

EOF
}

version() {
	cat <<EOF
$basename $(zenity --version)
EOF
	exit 0
}

while getopts "hVv" option; do
	case "${option}" in
		h) usage; exit 0;;
		V) version;;
		v) verbosity=1;;
	esac
done
shift $((OPTIND-1))

check_verbosity "message=(zenity --entry --text=Message --title='Share to Fediverse' \
	--ok-label=Send --cancel-label=Cancel)"
message=$(zenity --entry --text=Message --title="Share to Fediverse" \
	--ok-label=Send --cancel-label=Cancel)

if [ $? -eq 1 ]; then
	echo "$basename: cancelled by user"
	exit 1
fi

check_verbosity "toot post '$message'"
toot post "$message"

if [ $? -eq 1 ]; then
	echo "$basename: unable to post status"
	check_verbosity "notify-send --expire-time=5000 '$basename' 'Unable to post status'"
	notify-send --expire-time=5000 "$basename" "Unable to post status"
	exit 1
else
	echo "$basename: status post successful"
	check_verbosity "notify-send --expire-time=5000 '$basename' 'Status Post Successful'"
	notify-send --expire-time=5000 "$basename" "Status Post Successful"
fi

exit 0
