#!/bin/bash

# Tsubasa
# Script for sharing screenshots and/or staus updates using [ihabunek/toot](https://github.com/ihabunek/toot)

basename="$(basename $0)"
message=$(zenity --entry --text=Message --title="Share to Fediverse" \
	--ok-label=Send --cancel-label=Cancel)

if [ $? -eq 1 ]; then
	echo "$basename: cancelled by user"
	exit 1
fi

toot post "$message"

if [ $? -eq 1 ]; then
	echo "$basename: unable to post status"
	notify-send --expire-time=5000 "$basename" "Unable to post status"
	exit 1
else
	echo "$basename: status post successful"
	notify-send --expire-time=5000 "$basename" "Status Post Successful"
fi

exit 0
